# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71aa340c755d837c4a8376b4e17ac9aa407934a665392db8f191957a7e78b62b0d6145ca0fe214e5db2662c98b2f5555684d2edba764d9538616f32a6296d7de

test:
  secret_key_base: dec23b1db870e6377737c4246063cfd72554518177b4a7e8e02e0736cb4fd321c228fe649b1780a55e49bd92f379eb617af2ddca57982a6a84fc070eca5a480a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
